### ISSUE TITLE
This device tree works on the Moto g53 5G (XT2335-1) ?

### ISSUE THREAD

**Issue by D4yvid** [nattolecats/device_motorola_penang#1]
I didn't see any mention of it's SKU in the repository, and i have this device. If you need more information about the device, tell me and i'll send it to you

**Comment by nattolecats** [comment]
I think that's won't fully work on your device. This tree configured for Japanese edition.
But feel freely to you can fork it, and add sku support for your device. thanks

**Comment by nattolecats** [comment]
Thanks for you going to supports me. 
This tree is configured for Japanese variants. and it's personally-tree, so I'm not thinking to add another sku.
Maybe it's bootable on your device, but some settings should be adjust for fully works, I believe.
